### ISSUE TITLE
 PipeScript should be able to generate WebAssembly (.wat)

### ISSUE THREAD

**Issue by StartAutomating** [StartAutomating/PipeScript#239]
Since [WebAssembly supports block comments](https://webassembly.github.io/spec/core/text/lexical.html#comments), it should be relatively trivial to embed PipeScript within WebAssembly using:

~~~WAT
(;{
# your powershell code here
};)
~~~

This issue is not meant to fully resolve the hope mentioned in [this discussion thread](https://github.com/orgs/PowerShell/discussions/17339#discussioncomment-3725474).  It is only there to provide the groundwork for generation of .WAT files, in the same way that PipeScript can be used to generate many other file types.

**Comment by Ayanmullick** [comment]
Hi! 👋 Thanks for the work on WAT support. I have a related question/use case:

- I am trying to embed PowerShell directly in HTML using <script type="pwsh">…</script> blocks and a build task that parses those blocks and emits C# for a .NET WebAssembly app.
https://github.com/Ayanmullick/PS.NetWasmAzCosmos/blob/224f60217236a9e35b80b2ddc0641d6332b91549/src/wwwroot/index.html#L24C1-L28C12

- Could PipeScript support a similar pattern for HTML? For example:
> - Parse inline <script type="pwsh"> blocks in an HTML file.
> - Treat each block as PipeScript/PowerShell input and generate output alongside the rest of the HTML (or produce a companion file, e.g., CompiledPowerShell.g.cs or similar).

- If this is already possible, is there an example of PipeScript processing HTML inputs and extracting embedded PowerShell? If not, would you consider it in scope for future work, similar to how the WAT block-comment embedding is envisioned?

Thanks for considering!
