### ISSUE TITLE
exploring a real world use case with TF HCL

### ISSUE THREAD

**Issue by rismoney** [StartAutomating/PipeScript#240]
I recently came across your project.  Very interesting approach.  What I am wondering is, if I were to integrate this with terraform's HCL language, what kind of benefits would I be able to get.  HCL is a fairly dumbed-down and limited DSL language used mostly for instantiating cloud/hypervisor resources.  I am wondering if PipeScript by extension of real powershell programming capabilities can really enhance the capability there.  For instance, conditional logic, looping, and data structure handling "sucks" in TF's HCL, but can be really advantageous if boosted through powershell.

I welcome your thoughts on this.  Cheers, and hope all is well with you!

**Comment by StartAutomating** [comment]
@rismoney That would be a wonderful use case of PipeScript!

I've opened #241 to track this issue and should have it out shortly.
