### ISSUE TITLE
PipeScript GitHub Action should force -ErrorActionPreference to be continue

### ISSUE THREAD

**Issue by StartAutomating** [StartAutomating/PipeScript#378]
And yet, it should still fail a build if there are any build errors.

It _might_ be a good idea to allow an option to check in files that work (though prudence would demand it should not be the default).

**Comment by ninmonkey** [comment]
When trying to debug errors in Pipe(script/works) it might be useful to have `Export-Pipescript` let some exceptions bubble up. `Export-PipesScript -ErrorAction break` is ignored.

**Comment by StartAutomating** [comment]
Reopening for tracking:

While this does make -ErrorAction continue, build errors within a given file are not being converted into error records, and thus, the build is not failing when one file files.
