### ISSUE TITLE
Include should be able to exclude

### ISSUE THREAD

**Issue by StartAutomating** [StartAutomating/PipeScript#418]
Include already has an exclusion pattern.

This pattern should be customizable.

**Comment by ninmonkey** [comment]
Or the ability to pipe filenames that I pipe to Build-Pipescript
Or the ability to get the file name listing myself, like

```ps1
Find-BuildablePipescript -Include '*.ps.*' | ? Name -notmatch '\.ps.psd1$' | Build-Pipescript
```
