### ISSUE TITLE
Importing using Get-Content can accidentally break script because of whitespace

### ISSUE THREAD

**Issue by ninmonkey** [StartAutomating/PipeScript#419]
If I include files using transpile, I have to ensure I don't have implicit string joining.
I do not know whether this is a bug, or it joins on space instead of newline for a reason. If it's not a bug, maybe the user can set a default join option?
```html
<script>
<!--{
        Get-Content 'component.navigate.chartKind.js'
}-->
</script>
```

## Expected Result
```js
function doStuff() { 
    x = 10 // did stuff
    y = x + 10
    return y
}
```
## Actual Result when Implicit
```js
function doStuff() {     x = 10 // did stuff    y = x + 10    return y}
```
## Alternate invoke

```ps1
# broken parsing because of no newlines as default join
Get-Content 'foo.js'

# works when not using implicit joins
Get-Content 'foo.js' -raw
(Get-Content 'foo.js') -join "`n"
```

**Comment by StartAutomating** [comment]
@ninmonkey this is Get-Content's "problem".

By default, it reads line by line.

Get-Content -Raw will read all of it as a single string.

Changing $ofs for PipeScript doesn't make too much sense in my opinion, and I wouldn't want to put newlines in generated source by accident (I'd rather see this sort of bug from time to time).

Therefore, I'm going to close this issue.
