### ISSUE TITLE
`[Ast]/[ScriptBlock]`.IsEmpty

### ISSUE THREAD

**Issue by StartAutomating** [StartAutomating/PipeScript#494]
We should add a ScriptProperty to standardize a definition of ScriptBlock AST emptiness (as this is the source of small errors).

**Comment by ninmonkey** [comment]
Which kinds of empty? Ex: 

- Empty Literal, 
- Empty expression, 
- or whitespace only
- or empty result?
- empty `[FunctionInfo]` verses a `[ScriptBlock]`
 
I tried some conditions that don't touch AST.

- `{}` is empty
- `{ }` is not

I guess that makes sense - if it's doing `([string]{}).Length` . 

| Name | Value |
| - | - |
| `IsNullOrEmpty {}`         | True |0
| `IsNullOrEmpty { }`        | False |
| `IsNullOrWhiteSpace {}`    | True |
| `IsNullOrWhiteSpace { }`   | True |
| `IsNullOrEmpty $sb`        | True |
| `IsNullOrEmpty $sb2`       | False |
| `IsNullOrWhiteSpace $sb`   | True |
| `IsNullOrWhiteSpace $sb2`  | True |

```ps1
$sb = {}
$sb2 = { }
[ordered]@{
    'IsNullOrEmpty {} '        = [String]::IsNullOrEmpty( {} )
    'IsNullOrEmpty { } '       = [String]::IsNullOrEmpty( { } )
    'IsNullOrWhiteSpace {} '   = [String]::IsNullOrWhiteSpace( {} )
    'IsNullOrWhiteSpace { } '  = [String]::IsNullOrWhiteSpace( { } )
    'IsNullOrEmpty $sb '       = [String]::IsNullOrEmpty( $sb )
    'IsNullOrEmpty $sb2 '      = [String]::IsNullOrEmpty( $sb2 )
    'IsNullOrWhiteSpace $sb '  = [String]::IsNullOrWhiteSpace( $sb )
    'IsNullOrWhiteSpace $sb2 ' = [String]::IsNullOrWhiteSpace( $sb2 )
}|ft -auto
```
